### PR TITLE
Default Custom error message

### PR DESCRIPTION
**Pull request by m-weeks**
Added the ability to specify a default custom error message by setting `mongoose.SchemaTypes.Email.defaults.message`

### CODE REVIEW

**Comment by konsumer** [comment]
Looks good. I think it might be a good idea to add a model option for error message, too, but this looks fine for now.

**Comment by m-weeks** [comment]
@konsumer Thanks for merging! Are you planning on publishing this soon? I would like to use it in a project

**Comment by konsumer** [comment]
I'm travelling right now, but should be back in a few days and will do a publish then.

**Comment by adrianrios25** [comment]
Hi,

I tried this, but got an error

TypeError: Cannot set property 'message' of undefined

Below is my code:

var mongoose = require('mongoose');
require('mongoose-type-email');

mongoose.SchemaTypes.Email.defaults.message = 'Email address is invalid';

**Pull request merged**
